name: Release Drafter
on:
  push:
    branches:
      - "dev"

jobs:
  build:
    name:  Release Drafter
    runs-on: ubuntu-20.04
    steps:
      
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
